# Site settings
title: Skagway Opening Times
email: contact@vansintjan.net
description: > # this means to ignore newlines until "baseurl:"
  Skagway only has so many stores but I can't keep straight when they all open.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://simonv3.github.io/skagway-opening-times" # the base hostname & protocol for your site
twitter_username: simonv3
github_username:  simonv3

# Build settings
markdown: kramdown
